package vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Autor;
import modelo.Fecha;

/**
 *
 * @author Mao
 */
public class InterfazEditarAutor extends javax.swing.JDialog {
    
    private  int indice;
    
    String nombre, apellido, identificacion, nacionalidad, fecha;
    //Date fecha;

    /**
     * Creates new form InterfazEditarAutor
     */
    private static InterfazLibreria interfazLibreria;
    public InterfazEditarAutor(InterfazLibreria win) {
        
        interfazLibreria = win;
        initComponents();
        jDateChooser1.getDateEditor().setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditarNombreAutor = new javax.swing.JTextField();
        btnGuardarNuevoAutor = new javax.swing.JButton();
        lblEditarNombreAutor = new javax.swing.JLabel();
        lblEditarApellidoAutor1 = new javax.swing.JLabel();
        txtEditarApellidoAutor = new javax.swing.JTextField();
        lblEditarIdAutor = new javax.swing.JLabel();
        txtEditarIdAutor = new javax.swing.JTextField();
        lblEditarNacionalidadAutor = new javax.swing.JLabel();
        txtEditarNacionalidadAutor = new javax.swing.JTextField();
        lblEditarFechadAutor = new javax.swing.JLabel();
        btnCancelarNuevoAutor = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar autor");

        btnGuardarNuevoAutor.setText("Guardar");
        btnGuardarNuevoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevoAutorActionPerformed(evt);
            }
        });

        lblEditarNombreAutor.setText("Nombre del autor:");

        lblEditarApellidoAutor1.setText("Apellidos del autor:");

        lblEditarIdAutor.setText("Identificacion:");

        lblEditarNacionalidadAutor.setText("Nacionalidad:");

        lblEditarFechadAutor.setText("Nacionalidad:");

        btnCancelarNuevoAutor.setText("Cancelar");
        btnCancelarNuevoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNuevoAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEditarNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditarNombreAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEditarApellidoAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditarApellidoAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEditarIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditarIdAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEditarNacionalidadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEditarNacionalidadAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEditarFechadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnGuardarNuevoAutor)
                .addGap(65, 65, 65)
                .addComponent(btnCancelarNuevoAutor)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditarNombreAutor)
                    .addComponent(txtEditarNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditarApellidoAutor1)
                    .addComponent(txtEditarApellidoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditarIdAutor)
                    .addComponent(txtEditarIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditarNacionalidadAutor)
                    .addComponent(txtEditarNacionalidadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditarFechadAutor)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevoAutor)
                    .addComponent(btnCancelarNuevoAutor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevoAutorActionPerformed
        Autor autor = new Autor();
        nombre = txtEditarNombreAutor.getText();
        apellido = txtEditarApellidoAutor.getText();
        identificacion = txtEditarIdAutor.getText();
        nacionalidad = txtEditarNacionalidadAutor.getText();
        
        autor.cambiarNombre(nombre);
        autor.cambiarApellido(apellido);
        autor.cambiarIdentificacion(identificacion);
        autor.cambiarNacionalidad(nacionalidad);
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
        fecha = formatoFecha.format(jDateChooser1.getDate());
        //fecha = jDateChooser1.getDate();
        Fecha f = new Fecha();
        f.cambiarFecha(fecha);
        autor.cambiarFechaNacimiento(f);

        interfazLibreria.modificarAutor(indice,autor);
        interfazLibreria.model.setValueAt(autor.darNombre(), interfazLibreria.jtDatosAutor.getSelectedRow(), 0);
        interfazLibreria.model.setValueAt(autor.darApellido(), interfazLibreria.jtDatosAutor.getSelectedRow(), 1);
        interfazLibreria.model.setValueAt(autor.darIdentificacion(), interfazLibreria.jtDatosAutor.getSelectedRow(), 2);
        interfazLibreria.model.setValueAt(autor.darNacionalidad(), interfazLibreria.jtDatosAutor.getSelectedRow(), 3);
        interfazLibreria.model.setValueAt(autor.darFecha().darFechaCompleta(), interfazLibreria.jtDatosAutor.getSelectedRow(), 4);

        JOptionPane.showMessageDialog(this, "Edición exitosa!!!", "Seleccionar elemento", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarNuevoAutorActionPerformed

    private void btnCancelarNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNuevoAutorActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarNuevoAutorActionPerformed
    public void datosAutor(int i,Autor a){
        indice=i;
        txtEditarNombreAutor.setText(a.darNombre());
        txtEditarApellidoAutor.setText(a.darApellido());
        txtEditarIdAutor.setText(a.darIdentificacion());
        txtEditarNacionalidadAutor.setText(a.darNacionalidad());
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date f = formatoFecha.parse(a.darFecha().darFechaCompleta());
            jDateChooser1.setDate(f);
        } catch (ParseException ex) {
            Logger.getLogger(InterfazEditarAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarNuevoAutor;
    private javax.swing.JButton btnGuardarNuevoAutor;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblEditarApellidoAutor1;
    private javax.swing.JLabel lblEditarFechadAutor;
    private javax.swing.JLabel lblEditarIdAutor;
    private javax.swing.JLabel lblEditarNacionalidadAutor;
    private javax.swing.JLabel lblEditarNombreAutor;
    private javax.swing.JTextField txtEditarApellidoAutor;
    private javax.swing.JTextField txtEditarIdAutor;
    private javax.swing.JTextField txtEditarNacionalidadAutor;
    private javax.swing.JTextField txtEditarNombreAutor;
    // End of variables declaration//GEN-END:variables
}
