/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Autor;
import modelo.Editorial;
import modelo.Fecha;
import modelo.Imagen;
import modelo.Libreria;
import modelo.Libro;

/**
 *
 * @author Mao
 */
public class InterfazAgregarLibro extends javax.swing.JDialog {

    private InterfazLibreria interfazLibreria;

    private String nombre;

    private String idioma;

    private String fecha;

    private String imagen;

    private int cantidad;

    JFileChooser seleccionado;

    File archivo;

    byte[] bytesImg;

    /**
     * Creates new form InterfazAgregarLibro
     */
    public InterfazAgregarLibro(InterfazLibreria win) {
        interfazLibreria = win;
        seleccionado = new JFileChooser();
        this.setModal(true);
        initComponents();
        llenarAutor();
        llenarEditorial();
        jDateChooser1.getDateEditor().setEnabled(false);
    }

    public void llenarAutor() {
        ArrayList<Autor> lista = interfazLibreria.darListaAutor();
        for (int i = 0; i < lista.size(); i++) {
            jcAutorLibro.addItem(lista.get(i).darNombre());
        }
    }

    public void llenarEditorial() {
        ArrayList<Editorial> lista = interfazLibreria.darListaEditorial();
        for (int i = 0; i < lista.size(); i++) {
            jcEditorialLibro.addItem(lista.get(i).darNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jpAgregarLibro = new javax.swing.JPanel();
        lblNombreLibro = new javax.swing.JLabel();
        txtNombreLibro = new javax.swing.JTextField();
        lblIdiomaLibro = new javax.swing.JLabel();
        txtIdiomaLibro = new javax.swing.JTextField();
        lblCantidadLibro = new javax.swing.JLabel();
        txtCantidadLibro = new javax.swing.JTextField();
        lblAutorLibro = new javax.swing.JLabel();
        jcAutorLibro = new javax.swing.JComboBox();
        lblEditorialLibro = new javax.swing.JLabel();
        jcEditorialLibro = new javax.swing.JComboBox();
        lblImagenLibro = new javax.swing.JLabel();
        btnImagenLibro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarLibro = new javax.swing.JButton();
        btnCancelarLibro = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Libro");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jpAgregarLibro.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Libro"));

        lblNombreLibro.setText("Nombre del libro:");

        lblIdiomaLibro.setText("Idioma del libro:");

        lblCantidadLibro.setText("Cantidad:");

        lblAutorLibro.setText("Autor:");

        lblEditorialLibro.setText("Editorial:");

        lblImagenLibro.setText("Imagen:");

        btnImagenLibro.setText("Seleccionar imagen");
        btnImagenLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenLibroActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha publicacion:");

        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });

        btnCancelarLibro.setText("Cancelar");
        btnCancelarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAgregarLibroLayout = new javax.swing.GroupLayout(jpAgregarLibro);
        jpAgregarLibro.setLayout(jpAgregarLibroLayout);
        jpAgregarLibroLayout.setHorizontalGroup(
            jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnGuardarLibro)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEditorialLibro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutorLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCantidadLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(lblImagenLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jcAutorLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcEditorialLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnCancelarLibro))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImagenLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIdiomaLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAgregarLibroLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtIdiomaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jpAgregarLibroLayout.setVerticalGroup(
            jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpAgregarLibroLayout.createSequentialGroup()
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreLibro)
                            .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdiomaLibro)
                            .addComponent(txtIdiomaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadLibro)
                            .addComponent(txtCantidadLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutorLibro)
                            .addComponent(jcAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditorialLibro)
                            .addComponent(jcEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenLibro)
                    .addComponent(btnImagenLibro))
                .addGap(18, 18, 18)
                .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jpAgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarLibro)
                    .addComponent(btnCancelarLibro))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAgregarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAgregarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed

        try {
            nombre = txtNombreLibro.getText();
            idioma = txtIdiomaLibro.getText();
            cantidad = Integer.parseInt(txtCantidadLibro.getText());
            int indiceAutor = jcAutorLibro.getSelectedIndex();
            int indiceEditorial = jcEditorialLibro.getSelectedIndex();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            fecha = formatoFecha.format(jDateChooser1.getDate());
            Fecha unaFecha = new Fecha(fecha);
            Imagen unaImagen = new Imagen(archivo.getName());
            Autor unAutor = interfazLibreria.darAutor(indiceAutor);
            Editorial unaEditorial = interfazLibreria.darEditorial(indiceEditorial);
            Libro unLibro = new Libro(nombre, idioma, cantidad, unAutor, unaEditorial, unaImagen, unaFecha);
            interfazLibreria.agregarLibro(unLibro);
            interfazLibreria.modelLibro.addRow(new Object[]{unLibro.darNombre(),unLibro.darAutor().darNombre(),unLibro.darEditorial().darNombre(),unLibro.darCantidad(),unLibro.darCantidad(),unLibro.darFecha().darFechaCompleta()});
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Existe un error", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la imagen", "Error", JOptionPane.ERROR_MESSAGE);
        }
//        libreria.agregarLibro(unLibro);
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnImagenLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenLibroActionPerformed
        Imagen i = new Imagen();

        if (seleccionado.showDialog(null, "Abrir Imagen") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png") || archivo.getName().endsWith("gif")) {
                    bytesImg = i.cargarImagen(archivo.getAbsolutePath());
                    ImageIcon icono = new ImageIcon(bytesImg);
                    Image imagen = icono.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
                    icono = new ImageIcon(imagen);
                    jLabel2.setIcon(icono);
                    Path origen = Paths.get(archivo.getAbsolutePath());
                    Path destino = Paths.get("C:\\Users\\Mao\\Documents\\NetBeansProjects\\Libreria\\src\\img\\" + archivo.getName());
                    System.out.println("" + destino.toString());
                    try {
                        Files.copy(origen, destino, StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException ex) {
                        System.out.println(ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto o de imagen.");
                }
            }

        }
    }//GEN-LAST:event_btnImagenLibroActionPerformed

    private void btnCancelarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLibroActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarLibroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLibro;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JButton btnImagenLibro;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jcAutorLibro;
    private javax.swing.JComboBox jcEditorialLibro;
    private javax.swing.JPanel jpAgregarLibro;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblCantidadLibro;
    private javax.swing.JLabel lblEditorialLibro;
    private javax.swing.JLabel lblIdiomaLibro;
    private javax.swing.JLabel lblImagenLibro;
    private javax.swing.JLabel lblNombreLibro;
    private javax.swing.JTextField txtCantidadLibro;
    private javax.swing.JTextField txtIdiomaLibro;
    private javax.swing.JTextField txtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
