/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.Autor;
import modelo.Editorial;
import modelo.Libreria;

/**
 *
 * @author Mao
 */
public class InterfazLibreria extends javax.swing.JFrame{

    private Libreria libreria;
    DefaultTableModel model, modelEditorial;

    /**
     * Creates new form InterfazLibreria
     */
    public InterfazLibreria() {
        libreria = new Libreria();
        initComponents();
        
        model = (DefaultTableModel) jtDatosAutor.getModel();
        modelEditorial = (DefaultTableModel) jtDatosEditorial.getModel();
        setLocationRelativeTo(null);
    }

    public void mostrarTablaLibros() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Idioma");
        modelo.addColumn("Autor");
        modelo.addColumn("Editorial");
        modelo.addColumn("Precio");
        jtDatosLibro.setModel(modelo);

        String[] datos = new String[5];
        datos[0] = "Cien años de soledad";
        datos[1] = "Español";
        datos[2] = "Gabriel Garcia M.";
        datos[3] = "McGraw-Hill";
        datos[4] = "$" + String.valueOf(25000);
        modelo.addRow(datos);
    }

    public void mostrarTablaDetalleCompra() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Autor");
        modelo.addColumn("Editorial");
        modelo.addColumn("Subtotal");
        jtDetalleCopra.setModel(modelo);
    }

    public ArrayList<Editorial> darListaEditorial() {
        return libreria.darListaEditorial();
    }
    
    public void agregarEditorial(Editorial editorial){
        libreria.agregarEditorial(editorial);
    }
    
    void modificarEditorial(int indice, Editorial editorial) {
        libreria.modificarEditorial(indice, editorial);
    }
    
    public void eliminarEditorial(int indice){
        libreria.eliminarEditorial(indice);
    }

    public ArrayList<Autor> darListaAutor() {
        return libreria.darListaAutor();
    }

    public void modificarAutor(int i, Autor unAutor) {
        libreria.modificarAutor(i, unAutor);
    }

    public void agregarAutor(Autor autor) {
        libreria.agregarAutor(autor);
    }
    
    public void eliminarAutor(int indice){
        libreria.eliminarAutor(indice);
    }

//    public void mostrarTablaAutores() {
//        ArrayList<Autor> listaAutor = libreria.darListaAutor();
//        Iterator it = listaAutor.iterator();
//        while (it.hasNext()) {
//            Autor a = (Autor) it.next();
//            model.addRow(new Object[]{a.darNombre(), a.darApellido(), a.darIdentificacion(), a.darNacionalidad(), a.darFecha().darFechaCompleta()});
//        
//        }
//        
////        for (int i = 0; i < listaAutor.size(); i++) {
////            Autor a = (Autor) listaAutor.get(i);
////            model.addRow(new Object[]{a.darNombre(), a.darApellido(), a.darIdentificacion(), a.darNacionalidad(), a.darFecha().darFechaCompleta()});
////        }
//        
////        Object[] columns = {"Nombre", "Apellido", "Identificacion", "Nacionalidad", "Fecha nacimiento"};
////        modelo = new DefaultTableModel(null, columns);
////
////        for (int i = 0; i < listaAutor.size(); i++) {
////            Autor a = (Autor) listaAutor.get(i);
////            modelo.addRow(new Object[]{a.darNombre(), a.darApellido(), a.darIdentificacion(), a.darNacionalidad(), a.darFecha().darFechaCompleta()});
////        }
////        jtDatosAutor.setModel(modelo);
////        System.out.println("Tamaño de la lista: " + listaAutor.size());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanen = new javax.swing.JTabbedPane();
        jpLibro = new javax.swing.JPanel();
        pnlListaLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDatosLibro = new javax.swing.JTable();
        btnAgregarLibro = new javax.swing.JButton();
        btnEditarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnComprarLibro = new javax.swing.JButton();
        pnlDetalleCompra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDetalleCopra = new javax.swing.JTable();
        btnCancelarCompra = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jpCliente = new javax.swing.JPanel();
        jpEditorial = new javax.swing.JPanel();
        pnlDatosEditorial = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtDatosEditorial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarEditorial = new javax.swing.JButton();
        btnEditarEditorial = new javax.swing.JButton();
        btnEliminarEditorial = new javax.swing.JButton();
        jpAutor = new javax.swing.JPanel();
        pnlListaAutores = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDatosAutor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarAutor = new javax.swing.JButton();
        btnEditarAutor = new javax.swing.JButton();
        btnBuscarAutor = new javax.swing.JButton();
        btnEliminarAutor = new javax.swing.JButton();
        txtBuscarAutor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Store");
        setResizable(false);

        pnlListaLibros.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle del catálogo"));

        jtDatosLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDatosLibro);

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnEditarLibro.setText("Editar Libro");
        btnEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLibroActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar Libro");

        btnComprarLibro.setText("Comprar Libro");

        javax.swing.GroupLayout pnlListaLibrosLayout = new javax.swing.GroupLayout(pnlListaLibros);
        pnlListaLibros.setLayout(pnlListaLibrosLayout);
        pnlListaLibrosLayout.setHorizontalGroup(
            pnlListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlListaLibrosLayout.createSequentialGroup()
                        .addComponent(btnAgregarLibro)
                        .addGap(60, 60, 60)
                        .addComponent(btnEditarLibro)
                        .addGap(77, 77, 77)
                        .addComponent(btnEliminarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(btnComprarLibro)))
                .addContainerGap())
        );
        pnlListaLibrosLayout.setVerticalGroup(
            pnlListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlListaLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLibro)
                    .addComponent(btnEditarLibro)
                    .addComponent(btnEliminarLibro)
                    .addComponent(btnComprarLibro))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlDetalleCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle del carrito de compras"));

        jtDetalleCopra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtDetalleCopra.setEnabled(false);
        jScrollPane2.setViewportView(jtDetalleCopra);

        btnCancelarCompra.setText("Cancelar");

        lblTotal.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setText("$0");

        javax.swing.GroupLayout pnlDetalleCompraLayout = new javax.swing.GroupLayout(pnlDetalleCompra);
        pnlDetalleCompra.setLayout(pnlDetalleCompraLayout);
        pnlDetalleCompraLayout.setHorizontalGroup(
            pnlDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleCompraLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(pnlDetalleCompraLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        pnlDetalleCompraLayout.setVerticalGroup(
            pnlDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelarCompra))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpLibroLayout = new javax.swing.GroupLayout(jpLibro);
        jpLibro.setLayout(jpLibroLayout);
        jpLibroLayout.setHorizontalGroup(
            jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListaLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpLibroLayout.setVerticalGroup(
            jpLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanen.addTab("Libros", jpLibro);

        javax.swing.GroupLayout jpClienteLayout = new javax.swing.GroupLayout(jpCliente);
        jpCliente.setLayout(jpClienteLayout);
        jpClienteLayout.setHorizontalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jpClienteLayout.setVerticalGroup(
            jpClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPanen.addTab("Clientes", jpCliente);

        pnlDatosEditorial.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la editorial"));

        jtDatosEditorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtDatosEditorial);

        btnAgregarEditorial.setText("Agregar Editorial");
        btnAgregarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEditorialActionPerformed(evt);
            }
        });

        btnEditarEditorial.setText("Editar Editorial");
        btnEditarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEditorialActionPerformed(evt);
            }
        });

        btnEliminarEditorial.setText("Eliminar Editorial");
        btnEliminarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEditorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarEditorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnEditarEditorial)
                .addGap(35, 35, 35)
                .addComponent(btnEliminarEditorial)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEditorial)
                    .addComponent(btnEditarEditorial)
                    .addComponent(btnEliminarEditorial))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosEditorialLayout = new javax.swing.GroupLayout(pnlDatosEditorial);
        pnlDatosEditorial.setLayout(pnlDatosEditorialLayout);
        pnlDatosEditorialLayout.setHorizontalGroup(
            pnlDatosEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEditorialLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlDatosEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        pnlDatosEditorialLayout.setVerticalGroup(
            pnlDatosEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEditorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpEditorialLayout = new javax.swing.GroupLayout(jpEditorial);
        jpEditorial.setLayout(jpEditorialLayout);
        jpEditorialLayout.setHorizontalGroup(
            jpEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpEditorialLayout.setVerticalGroup(
            jpEditorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanen.addTab("Editoriales", jpEditorial);

        pnlListaAutores.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del autor"));

        jtDatosAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Nacionalidad", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtDatosAutor);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregarAutor.setText("Agregar Autor");
        btnAgregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAutorActionPerformed(evt);
            }
        });

        btnEditarAutor.setText("Editar Autor");
        btnEditarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAutorActionPerformed(evt);
            }
        });

        btnBuscarAutor.setText("Buscar");
        btnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorActionPerformed(evt);
            }
        });

        btnEliminarAutor.setText("Eliminar Autor");
        btnEliminarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAgregarAutor)
                .addGap(93, 93, 93)
                .addComponent(btnEditarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarAutor)
                        .addGap(73, 73, 73)
                        .addComponent(btnEliminarAutor))
                    .addComponent(txtBuscarAutor))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(txtBuscarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAutor)
                    .addComponent(btnEliminarAutor)
                    .addComponent(btnBuscarAutor)
                    .addComponent(btnEditarAutor))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout pnlListaAutoresLayout = new javax.swing.GroupLayout(pnlListaAutores);
        pnlListaAutores.setLayout(pnlListaAutoresLayout);
        pnlListaAutoresLayout.setHorizontalGroup(
            pnlListaAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlListaAutoresLayout.setVerticalGroup(
            pnlListaAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jpAutorLayout = new javax.swing.GroupLayout(jpAutor);
        jpAutor.setLayout(jpAutorLayout);
        jpAutorLayout.setHorizontalGroup(
            jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpAutorLayout.setVerticalGroup(
            jpAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanen.addTab("Autores", jpAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanen, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLibroActionPerformed

        InterfazEditarLibro edit = new InterfazEditarLibro();
        edit.setEnabled(true);
        edit.setLocationRelativeTo(this);
        edit.setVisible(true);
    }//GEN-LAST:event_btnEditarLibroActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed

        InterfazAgregarLibro win = new InterfazAgregarLibro(this);
        win.setEnabled(true);
        win.setLocationRelativeTo(this);
//        win.setModal(true);
        win.setVisible(true);
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnAgregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAutorActionPerformed
        InterfazAgegarAutor ia = new InterfazAgegarAutor(this);
        ia.setEnabled(true);
        ia.setLocationRelativeTo(this);
        ia.setVisible(true);

    }//GEN-LAST:event_btnAgregarAutorActionPerformed

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    private void btnEditarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAutorActionPerformed
        ArrayList<Autor> lista = libreria.darListaAutor();
        if(jtDatosAutor.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista", "Seleccionar elemento", JOptionPane.ERROR_MESSAGE);
        }else{
            Autor a = (Autor) lista.get(jtDatosAutor.getSelectedRow());
            InterfazEditarAutor ed = new InterfazEditarAutor(this);
            ed.datosAutor(jtDatosAutor.getSelectedRow(), a);
            ed.setEnabled(true);
            ed.setLocationRelativeTo(this);
            ed.setVisible(true);
           }
    }//GEN-LAST:event_btnEditarAutorActionPerformed

    private void btnAgregarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEditorialActionPerformed
        InterfazAgregarEditorial ia = new InterfazAgregarEditorial(this);
        ia.setEnabled(true);
        ia.setLocationRelativeTo(this);
        ia.setVisible(true);
    }//GEN-LAST:event_btnAgregarEditorialActionPerformed

    private void btnEditarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEditorialActionPerformed
        ArrayList<Editorial> lista = libreria.darListaEditorial();
        if(jtDatosEditorial.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista", "Seleccionar elemento", JOptionPane.ERROR_MESSAGE);
        }else{
            Editorial e = (Editorial) lista.get(jtDatosEditorial.getSelectedRow());
            InterfazEditarEditorial ed = new InterfazEditarEditorial(this);
            ed.datosEditorial(jtDatosEditorial.getSelectedRow(), e);
            ed.setEnabled(true);
            ed.setLocationRelativeTo(this);
            ed.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarEditorialActionPerformed

    private void btnEliminarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEditorialActionPerformed
        if(jtDatosEditorial.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista", "Eliminar elemento", JOptionPane.ERROR_MESSAGE);
        }else{
            int indice = jtDatosEditorial.getSelectedRow();
            eliminarEditorial(indice);
            modelEditorial.removeRow(indice);
            JOptionPane.showMessageDialog(this, "Eliminación exitosa!!!", "Eliminar elemento", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarEditorialActionPerformed

    private void btnEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutorActionPerformed
        if(jtDatosAutor.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista", "Eliminar elemento", JOptionPane.ERROR_MESSAGE);
        }else{
            int indice = jtDatosAutor.getSelectedRow();
            eliminarAutor(indice);
            model.removeRow(indice);
            JOptionPane.showMessageDialog(this, "Eliminación exitosa!!!", "Eliminar elemento", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAutor;
    private javax.swing.JButton btnAgregarEditorial;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnComprarLibro;
    private javax.swing.JButton btnEditarAutor;
    private javax.swing.JButton btnEditarEditorial;
    private javax.swing.JButton btnEditarLibro;
    private javax.swing.JButton btnEliminarAutor;
    private javax.swing.JButton btnEliminarEditorial;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPanen;
    private javax.swing.JPanel jpAutor;
    private javax.swing.JPanel jpCliente;
    private javax.swing.JPanel jpEditorial;
    private javax.swing.JPanel jpLibro;
    public javax.swing.JTable jtDatosAutor;
    public javax.swing.JTable jtDatosEditorial;
    private javax.swing.JTable jtDatosLibro;
    private javax.swing.JTable jtDetalleCopra;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDatosEditorial;
    private javax.swing.JPanel pnlDetalleCompra;
    private javax.swing.JPanel pnlListaAutores;
    private javax.swing.JPanel pnlListaLibros;
    private javax.swing.JTextField txtBuscarAutor;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

   

}
